### PR TITLE
Add pulsar and platform

### LINKED ISSUE #7: Add pulsar and SN platform to homebrew
We should consider adding both `pulsar` and `sn-platform` into homebrew.

### PR DESCRIPTION
**Pull request by zymap**
---

Fixes #7

### CODE REVIEW

**Comment by zymap** [comment]
I am not sure why the CI can not pass. 

Install pulsar:
```
brew install https://gist.githubusercontent.com/zymap/0029e7dd0a07579d22885dfa856fa7c1/raw/2b7b9ce55c8f4c87ec785905abfd42ec1bc03ac7/pulsar.rb
```

Install platform:
```
brew install https://gist.githubusercontent.com/zymap/e8b676d7da9c25226dec075f126d34d3/raw/886f9c78b2f782f6bde14f69cb60f9cf6891faa3/platform.rb
brew install 
```

**Comment by jiazhai** [comment]
@zymap to taking care of it.

**Comment by zymap** [comment]
I will fix the style problem later. But I am not sure why the test can not pass. 
The failed test before tells me to look at the rabbitmq install way. But it seems does not work well here. 

It' might take a long time to check it, so I will do it later.

**Comment by zymap** [comment]
We can merge this PR for now and update the CI with another PR. #13

**Review by jiazhai — APPROVED** [review]

**Pull request merged**
